/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as OTokenRouteImport } from './routes/o.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OTokenRoute = OTokenRouteImport.update({
  id: '/o/$token',
  path: '/o/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pitch': typeof PitchRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pitch': typeof PitchRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pitch': typeof PitchRoute
  '/c/$token': typeof CTokenRoute
  '/d/$token': typeof DTokenRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pitch' | '/c/$token' | '/d/$token' | '/o/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pitch' | '/c/$token' | '/d/$token' | '/o/$token'
  id: '__root__' | '/' | '/pitch' | '/c/$token' | '/d/$token' | '/o/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PitchRoute: typeof PitchRoute
  CTokenRoute: typeof CTokenRoute
  DTokenRoute: typeof DTokenRoute
  OTokenRoute: typeof OTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$token': {
      id: '/o/$token'
      path: '/o/$token'
      fullPath: '/o/$token'
      preLoaderRoute: typeof OTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PitchRoute: PitchRoute,
  CTokenRoute: CTokenRoute,
  DTokenRoute: DTokenRoute,
  OTokenRoute: OTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
